# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 44cee46ac5fc170aeea2e989650c7931c6a85259a0f95252524251b7966cc82e200f09709bf86b61205dedbc8d7c9774dbb1c043f20d20347f909f30677ebf69

test:
  secret_key_base: 24d5a1cb61f247b0f47e52d4c1902cfc904fe7431fd600ed67a7de634731f6428057b95a0ba636b4c958769454045439d689d1b7d27b2d81cade3ef5ea15d176

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>






  development:
    gmail_username: <%= ENV["GMAIL_USERNAME"] %>
    gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
    secret_key_base: (not shown)

  test:
    secret_key_base: (not shown)

  # Do not keep production secrets in the repository,
  # instead read values from the environment.
  production:
    gmail_username: <%= ENV["GMAIL_USERNAME"] %>
    gmail_password: <%= ENV["GMAIL_PASSWORD"] %>
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>